name: libdsm
description: An all platform wrapper for the libdsm(Defective SMB) library https://videolabs.github.io/libdsm/
version: 1.2.0
homepage: https://github.com/biezhihua/libdsm

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: open.flutter.libdsm
        pluginClass: DsmPlugin
      ios:
        pluginClass: DsmPlugin
